build: fix build failure due to missing AEncUpdateFrame
mfx_enctools_aenc.cpp:(.text+0x51e): undefined reference to `AEncUpdateFrame'

Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>